server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: timeseries-database-service

  influx:
    url: ${SPRING_INFLUX_URL:http://localhost:8086}
    token: ${SPRING_INFLUX_TOKEN:my-super-secret-auth-token}
    org: ${INFLUX_ORG:nais_org}
    bucket: ${INFLUX_BUCKET:nais_bucket}
    user: ${INFLUX_USER:nais}
    password: ${INFLUX_PASSWORD:password}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    healthcheck:
      enabled: false
  instance:
    prefer-ip-address: true

# (Opcionalno) management/actuator endpoints ako koristiš:
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
#   endpoint:
#     health:
#       show-details: when_authorized
