# src/main/resources/application.yml
server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: book-saga-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

app:
  graphBaseUrl: ${APP_GRAPHBASEURL:http://graph-service:8081}
  tsBaseUrl: ${APP_TSBASEURL:http://timeseries-service:8082}

clients:
  graph:
    base-url: http://graph-service:8081
  ts:
    base-url: http://timeseries-service:8082
