# src/main/resources/application.yml
server:
  port: 8085


spring:
  application:
    name: book-saga-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

app:
  graphBaseUrl: ${APP_GRAPHBASEURL:http://graph-service:9050}
  tsBaseUrl: ${APP_TSBASEURL:http://timeseries-service:8082}

clients:
  graph:
    base-url: http://graph-service:9050
  ts:
    base-url: http://timeseries-service:8082

